name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
# Permissions applied here would be effected on all jobs
# permissions:
jobs:
  assign-label:
    # permissions applied here would only be local to this job
    # once this permission is set, only this permission is granted, and the others are not granted
    permissions:       
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{
              "labels": ["bug"]
            }' \
          --fail